### PR TITLE
More Mac fixes

### PR DESCRIPTION
**Pull request by asylvest**
@ayoungs can you see if this branch builds successfully on your platform?  You shouldn't have to do `--disable-csm` anymore either (fixed one more spot in that check I think)

FYI @JonathanMeans

### CODE REVIEW

**Comment by ayoungs** [comment]
python waf build
  File "externals/coda-oss/build/waf", line 163, in <module>
  File "/Users/andyyoungs/Documents/swdev/six-library-osx/six-library/six-library/externals/coda-oss/build/.waf3-1.7.14-6b92f3c95d8c1bad60826036bf26d63f/waflib/Scripting.py", line 87, in waf_entry_point
    set_main_module(Context.run_dir+os.sep+Context.WSCRIPT_FILE)
  File "/Users/andyyoungs/Documents/swdev/six-library-osx/six-library/six-library/externals/coda-oss/build/.waf3-1.7.14-6b92f3c95d8c1bad60826036bf26d63f/waflib/Scripting.py", line 112, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/Users/andyyoungs/Documents/swdev/six-library-osx/six-library/six-library/externals/coda-oss/build/.waf3-1.7.14-6b92f3c95d8c1bad60826036bf26d63f/waflib/Context.py", line 275, in load_module
    raise Errors.WafError('Could not read the file %r'%path)

**Comment by ayoungs** [comment]
That was a problem copying old build.py.  A full clean clone.
Disabling CSM as it is not supported on this platform
Unsupported platform darwin
Andys-MBP:six-library andyyoungs$ python waf build
The project was not configured: run "waf configure" first!
I still have to --disable-csm
Then still:
../six/modules/c++/six/source/NITFWriteControl.cpp:463:43: error: ambiguous conversion for static_cast from 'six::Parameter' to 'size_t' (aka 'unsigned long')
        const size_t optNumRowsPerBlock = static_cast<size_t>(
../six/modules/c++/six/source/NITFWriteControl.cpp:484:43: error: ambiguous conversion for static_cast from 'six::Parameter' to 'size_t' (aka 'unsigned long')
        const size_t optNumColsPerBlock = static_cast<size_t>(
../six/modules/c++/six/source/NITFWriteControl.cpp:740:18: error: conversion from 'six::Parameter' to 'const size_t' (aka 'const unsigned long') is ambiguous
    const size_t bufferSize =
../six/modules/c++/six/source/NITFWriteControl.cpp:826:18: error: conversion from 'six::Parameter' to 'const size_t' (aka 'const unsigned long') is ambiguous
    const size_t bufferSize =

Wow almost there!  Awesome job!

**Comment by ayoungs** [comment]
copying the fixed up build.py in, then that builds all the way through to completion.

**Comment by ayoungs** [comment]
This is working smoothly with a fresh clone.  configures and build fine.
The last two things I'll continue to dig into are how to get rid of (use libc++):
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]

**Comment by asylvest** [comment]
OK cool - thanks for confirming @ayoungs.  Merging!

**Pull request merged**
