### PR TITLE
SIX 3.3.1

### PR DESCRIPTION
**Pull request by bzhang162**
Merging changes from high side to six library. When building, there is a warning that can be ignored (shows up as an error) and a failed unit test that were approved by team lead.

Changes:
- Changed how support array data is written
- Bug fixes in XML parser
- Reduced max number of float digits recorded in coda-oss

### CODE REVIEW

**Comment by bzhang162** [comment]
@adam-beauchamp @dave-starinshak 

working with riley bohr to look into coda-oss change and if it necessary in that form (for Dave: this was for the ticket to reduce the number of float digits kept), will let you know if/when there's an update. Thanks.

**Comment by bzhang162** [comment]
@adam-beauchamp 

After talking with the people who worked on the ticket and my team lead, I think its good to approve. Riley Bohr said you can talk to him for additional concerns

**Comment by adam-beauchamp** [comment]
@bzhang162 can you edit this PR to be against the main branch instead of this release?

**Comment by bzhang162** [comment]
@adam-beauchamp 

The main branch is significantly different from the release branch, so I dont think you would want to push it into there. Alternatively if you could create a random new branch from release/3.3.0 called 'SIX-3.3.1' I could push it there instead. I will let others know where to update from for the future.

**Pull request closed without merging**
